[tools]
selene = { source = "Kampfkarren/selene", version = "0.20.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.14.2" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
wally = { source = "upliftgames/wally", version = "0.3.1" }
